# Программы охватывающие внешние связи проекта

In [1]:
import pandas
import shutil
import logging

from os.path import basename
from datetime import datetime
from collections import Counter
from collections import defaultdict

In [2]:
from src.logging_config import setup_logging

unixtime = round(datetime.now().timestamp())
app_name = "ВнешниеПодключения"
setup_logging(app_name)

logger = logging.getLogger(__name__)
logger.info(f"Запуск приложения: {app_name}, выходные скрипты отмечены как {unixtime}")

## Подключение проектируемого объекта

In [3]:
from src.station import config

station = config.get_station()

In [4]:
main_file = station.scheme_file
cable_file = station.cable_set_file
output_dir = station.OUTPUT_DIR
plot_dir = station.PLOT_DIR

## Импортирование вспомогательных функций

### Функции работающие со структурой clemmnic_data

In [5]:
from src.out_connect.pandas import make_clemmnic_list

### Функции работающие со структурой contact и device

In [6]:
from src.out_connect.contact import make_contact_list
from src.out_connect.device import make_device_list

### Класс CableConnection формирующий кабеля

In [7]:
from src.out_connect.cable_connection import make_cable_connection

### Функции работы с исходной структурой Pandas

In [8]:
from src.out_connect.pandas import read_project_data

### Функции формарования КЖ и списка жил

In [9]:
from src.out_connect.cable_journal import make_wires_journal
from src.out_connect.cable_journal import make_cable_journal
from src.out_connect.cable_journal import total_length_journal
from src.out_connect.cable_journal import count_section_journal
from src.out_connect.cable_journal import shrink_long_string

### Построение монтажных схем

In [10]:
import src.out_connect.montage_cable as montage_cable
from src.out_connect import isolation_cables

### Прочие функции

In [11]:
from src.station.misc import get_short_cabinet_name
from src.out_connect.clemmnic import used_clemms
from src.out_connect.pandas import used_wires

from src.out_connect.general import device_list
from src.out_connect.general import make_cabinet_table
from src.out_connect.general import view_devices_with_contacts
from src.out_connect.general import print_work_scheme
from src.out_connect.general import print_schemes_name

import src.plot_table as pl
from src.plot_table import fit_data

from src.elements import AutocadElements

from src.misc import safe_to_csv
from src.misc import safe_to_excel
from src.misc import safe_excel_writer

## Чтение исходной схемы и инициализация основных структур

In [12]:
project_data = read_project_data(station)

In [13]:
contact_data = make_contact_list(project_data, station)
device_data = make_device_list(project_data, station)

In [14]:
clemmnic_data = make_clemmnic_list(project_data, station)

In [15]:
cables_collection = make_cable_connection(clemmnic_data, station)

### Отладочная информация о работе алгоритма

In [16]:
columns_clemmnic_data = [
    "wire",
    "clemmnic",
    "clemma",
    "cabin",
    "cabel",
    "inner_wire",
    "section",
    "type_cabel",
    "process",
    "number",
    "direction",
]
safe_to_csv(pandas.DataFrame(clemmnic_data, columns=columns_clemmnic_data).sort_values(
    by=["cabin", "clemmnic", "clemma"]
), f"{output_dir}/Отладка-{unixtime}.csv")

#### Краткое содержание clemmnic_data

In [17]:
pandas.DataFrame(clemmnic_data, columns=columns_clemmnic_data)

,wire,clemmnic,clemma,cabin,cabel,inner_wire,section,type_cabel,process,number,direction
0,A1,X1,1,01,к32,A1,50.0,АВВГ,0,0,#0122
1,B1,X1,2,01,к32,B1,50.0,АВВГ,0,0,#0122
2,C1,X1,3,01,к32,C1,50.0,АВВГ,0,0,#0122
3,N,X1,4,01,к32,N,25.0,АВВГ,0,0,#0122
4,A2,X1,5,01,к33,A2,50.0,АВВГ,0,0,#0121
...,...,...,...,...,...,...,...,...,...,...,...
804,923,X0,13,73,NaN,923,1.5,КВВГЭнг(A)-LS,0,0,NaN
805,925,X0,14,73,NaN,925,1.5,КВВГЭнг(A)-LS,0,0,NaN
806,A12,X1,67,74,NaN,NaN,1.5,КВВГЭнг(A)-LS,0,0,NaN
807,A14,X1,68,74,NaN,NaN,1.5,КВВГЭнг(A)-LS,0,0,NaN
808,A12,X1,67,75,NaN,NaN,1.5,КВВГЭнг(A)-LS,0,0,NaN

#### Клеммники с различающимися внешними и внутренними жилами

In [18]:
def different_wires(station, clemmnic_data):
    df = pandas.DataFrame()
    for cabine in station.show_contacts_cabines():
        df = pandas.concat([df, pandas.DataFrame(clemmnic_data.different_wires(cabine))])
    return df
different_wires(station, clemmnic_data)

   Шкаф Клеммник Внешняя Внутренняя Лист
0    01     X2:2    A011       A012  2.1
1    01     X2:4    B011       B012  2.1
2    01     X2:6    C011       C012  2.1
3    01     X5:1  1-HA03       HA03  2.6
4    01     X5:4  1-HA04       HA04  2.6
..  ...      ...     ...        ...  ...
22   06     X3:5   9(11)        A14  7.2
23   06     X3:8     NaN        A17  7.3
24   06     X3:9     NaN        A18  7.3
25   06    X5:10     923        NaN  7.3
26   06     X5:9     921        NaN  7.3

[122 rows x 5 columns]

#### Контакты, которые задублированы

In [19]:
contact_data.check_intersection(station, device_data)

ККТ 1ВТ
device.device='KSL', c.clemma='1', c.page='3.3', c.inner_wire='8141'
device.device='KSL', c.clemma='1', c.page='3.3', c.inner_wire='8141'
device.device='KSL', c.clemma='1', c.page='3.3', c.inner_wire='8141'
device.device='KSL', c.clemma='1', c.page='3.3', c.inner_wire='8141'
device.device='KSL', c.clemma='1', c.page='3.3', c.inner_wire='8141'
device.device='KSL', c.clemma='5', c.page='3.3', c.inner_wire='8007'
device.device='KSL', c.clemma='5', c.page='3.3', c.inner_wire='8007'
device.device='KSL', c.clemma='5', c.page='3.3', c.inner_wire='8007'
device.device='KSL', c.clemma='5', c.page='3.3', c.inner_wire='8007'
device.device='KSL', c.clemma='5', c.page='3.3', c.inner_wire='8003'

Пр.шк.
device.device='KHL5', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KHL5', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KHL20', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KHL20', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KL1', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KL1', c.clemma='11', c.page='2.7', c.inner_wire='K011'
device.device='KHL16', c.clemma='11', c.page='2.7', c.inner_wire='+24В'
device.device='KHL16', c.clemma='11', c.page='2.7', c.inner_wire='+24В'

ЦЩУ п.4
device.device='KHL', c.clemma='6', c.page='4.2', c.inner_wire=''
device.device='KHL', c.clemma='6', c.page='4.3', c.inner_wire='0ВT01k009'

#### Кабели, для которых не найдена пара

In [20]:
pdm = pandas.DataFrame(clemmnic_data, columns=columns_clemmnic_data)
pandas.set_option("display.max_rows", None)
not_defined_cable = pdm[(pdm.process == 0) & (~pdm.cabel.isna())].sort_values(
    by=["wire", "cabel", "cabin"]
)
not_defined_cable

,wire,clemmnic,clemma,cabin,cabel,inner_wire,section,type_cabel,process,number,direction
76,1-HA03,X5,1,01,1GT-107,HA03,1.5,КВВГЭнг(A)-LS,0,0,#0133
85,1-HA04,X5,4,01,1GT-107,HA04,1.5,КВВГЭнг(A)-LS,0,0,#0133
410,10701,X3,10,06,0BT02k191,10701,1.5,КВВГЭнг(A)-LS,0,0,#0339
719,10701,X2,36,39,0BT02k191,10701,1.5,КВВГЭнг(A)-LS,0,0,#0339
477,8003,X3,6,15,1BT-300,8003,1.5,КВВГЭнг(A)-LS,0,0,#1526
557,8141,XT,4,26,1BT-300,8141,1.5,КВВГЭнг(A)-LS,0,0,#1526
414,9(11),X3,5,06,0BT02k191,A14,1.5,КВВГЭнг(A)-LS,0,0,#0339
717,9(11),X1,126,39,0BT02k191,9(11),1.5,КВВГЭнг(A)-LS,0,0,#0339
437,921,X5,9,06,0BT02k191,NaN,1.5,КВВГЭнг(A)-LS,0,0,#0339
720,921,X2,39,39,0BT02k191,921,1.5,КВВГЭнг(A)-LS,0,0,#0339
429,923,X5,10,06,0BT02k191,NaN,1.5,КВВГЭнг(A)-LS,0,0,#0339
713,923,X0,51,39,0BT02k191,923,1.5,КВВГЭнг(A)-LS,0,0,#0339
712,925,X0,46,39,0BT02k191,925,1.5,КВВГЭнг(A)-LS,0,0,#0339
474,A1,X3,4,15,1BT-300,A1,1.5,КВВГЭнг(A)-LS,0,0,#1526
213,A1,X1,1,04,к100,A1,50.0,АВВГ,0,0,#0447
749,A1,SF10,2,47,к100,A1,120.0,АВВГ,0,0,#0447
0,A1,X1,1,01,к32,A1,50.0,АВВГ,0,0,#0122
529,A1,SF10,2,22,к32,A1,95.0,АВВГ,0,0,#0122
217,A2,X1,5,04,к101,A2,50.0,АВВГ,0,0,#0448
753,A2,SF10,2,48,к101,A2,120.0,АВВГ,0,0,#0448
4,A2,X1,5,01,к33,A2,50.0,АВВГ,0,0,#0121
525,A2,SF10,2,21,к33,A2,95.0,АВВГ,0,0,#0121
214,B1,X1,2,04,к100,B1,50.0,АВВГ,0,0,#0447
750,B1,SF10,4,47,к100,B1,120.0,АВВГ,0,0,#0447
1,B1,X1,2,01,к32,B1,50.0,АВВГ,0,0,#0122
530,B1,SF10,4,22,к32,B1,95.0,АВВГ,0,0,#0122
218,B2,X1,6,04,к101,B2,50.0,АВВГ,0,0,#0448
754,B2,SF10,4,48,к101,B2,120.0,АВВГ,0,0,#0448
5,B2,X1,6,01,к33,B2,50.0,АВВГ,0,0,#0121
526,B2,SF10,4,21,к33,B2,95.0,АВВГ,0,0,#0121
409,B4(1),X3,1,06,0BT02k191,A12,1.5,КВВГЭнг(A)-LS,0,0,#0339
714,B4(1),X1,124,39,0BT02k191,B4(1),1.5,КВВГЭнг(A)-LS,0,0,#0339
215,C1,X1,3,04,к100,C1,50.0,АВВГ,0,0,#0447
751,C1,SF10,6,47,к100,C1,120.0,АВВГ,0,0,#0447
2,C1,X1,3,01,к32,C1,50.0,АВВГ,0,0,#0122
531,C1,SF10,6,22,к32,C1,95.0,АВВГ,0,0,#0122
219,C2,X1,7,04,к101,C2,50.0,АВВГ,0,0,#0448
755,C2,SF10,6,48,к101,C2,120.0,АВВГ,0,0,#0448
6,C2,X1,7,01,к33,C2,50.0,АВВГ,0,0,#0121
527,C2,SF10,6,21,к33,C2,95.0,АВВГ,0,0,#0121
216,N,X1,4,04,к100,N,25.0,АВВГ,0,0,#0447
752,N,SF10,N,47,к100,N,120.0,АВВГ,0,0,#0447
220,N,X1,8,04,к101,N,25.0,АВВГ,0,0,#0448
756,N,SF10,N,48,к101,N,120.0,АВВГ,0,0,#0448
3,N,X1,4,01,к32,N,25.0,АВВГ,0,0,#0122
532,N,SF10,N,22,к32,N,95.0,АВВГ,0,0,#0122
7,N,X1,8,01,к33,N,25.0,АВВГ,0,0,#0121
528,N,SF10,N,21,к33,N,95.0,АВВГ,0,0,#0121
83,Р11.2-А,X5,2,01,1GT-107,Р11.2-А,1.5,КВВГЭнг(A)-LS,0,0,#0133
86,Р11.2-Б,X5,5,01,1GT-107,Р11.2-Б,1.5,КВВГЭнг(A)-LS,0,0,#0133
84,Р11.3-А,X5,3,01,1GT-107,Р11.3-А,1.5,КВВГЭнг(A)-LS,0,0,#0133
87,Р11.3-Б,X5,6,01,1GT-107,Р11.3-Б,1.5,КВВГЭнг(A)-LS,0,0,#0133
267,Ц101,X3,3,04,1GT-331,Ц101,1.5,КВВГЭнг(A)-LS,0,0,#0128
576,Ц101,X1,3,28,1GT-331,Ц101,1.5,КВВГЭнг(A)-LS,0,0,#0128
746,Ц101,X1,35,46,1GT-331,Ц101,1.5,КВВГЭнг(A)-LS,0,0,#0128
245,Ц101,X3,1,04,ED-1GT-105,Ц101,1.5,КВВГЭнг(A)-LS,0,0,#0114
277,Ц102,X3,5,04,ED-1GT-105,Ц102,1.5,КВВГЭнг(A)-LS,0,0,#0114
281,Ц127,X3,9,04,1GT-331,Ц127,1.5,КВВГЭнг(A)-LS,0,0,#0128
745,Ц127,X1,34,46,1GT-331,Ц127,1.5,КВВГЭнг(A)-LS,0,0,#0128
254,Ц133,X3,18,04,1GT-331,Ц133,1.5,КВВГЭнг(A)-LS,0,0,#0128
740,Ц133,X1,21,46,1GT-331,Ц133,1.5,КВВГЭнг(A)-LS,0,0,#0128

In [21]:
def check_cable(df):
    cable_not_define = []
    for i, row in df.iterrows():
        if row.cabel not in station.preset_cables():
            cable_not_define.append(row.cabel)
    if cable_not_define:
        print(df[df.cabel.isin(cable_not_define)].to_string())
        raise Exception(
            """Определи пары для всех направлений или спряч их в
        схеме! Направления, для которых нет пар могут быть только кабелями
        из других разделв проекта. И они должны быть явно указаны в методе
        station.preset_cables()"""
        )

In [22]:
check_cable(not_defined_cable)

#### Кабели, для которых нет напрвления

In [23]:
pdm = pandas.DataFrame(clemmnic_data, columns=columns_clemmnic_data)
pandas.set_option("display.max_rows", None)
pdm[(pdm.direction.isna()) & (~pdm.cabel.isna())]

Empty DataFrame
Columns: [wire, clemmnic, clemma, cabin, cabel, inner_wire, section, type_cabel, process, number, direction]
Index: []

In [24]:
pandas.set_option("display.max_rows", 60)
pandas.get_option("display.max_rows")

60

#### Краткое содержание cables_collection

In [25]:
cables_collection.debug(unixtime)

,НАПРАВЛЕНИЕ,ЖИЛА,КЛЕММНИК1,ВИРТ_КЛЕММНИК1,КЛЕММНИК2,ВИРТ_КЛЕММНИК2,СЕЧЕНИЕ,ТИП_КАБЕЛЯ,НОМЕР,КАБЕЛЬ
0,#0132,8001,X6,X6,1Т,1Т,1.5,КВВГЭнг(A)-LS,1,AOT-0132/1
1,#0132,8002,X6,X6,1Т,1Т,1.5,КВВГЭнг(A)-LS,1,AOT-0132/1
2,#0209,A1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0209/1
3,#0209,B1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0209/1
4,#0209,C1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0209/1
5,#0209,N,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0209/1
6,#0210,A2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0210/1
7,#0210,B2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0210/1
8,#0210,C2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0210/1
9,#0210,N,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0210/1
10,#0232,8001,X4,X4,1ВТ,1ВТ,1.5,КВВГЭнг(A)-LS,1,AOT-0232/1
11,#0232,8002,X4,X4,1ВТ,1ВТ,1.5,КВВГЭнг(A)-LS,1,AOT-0232/1
12,#0330,A1,X1,X1,АВ2,АВ2,6.0,ВВГнг(А)-LS,1,AOT-0330/1
13,#0330,B1,X1,X1,АВ2,АВ2,6.0,ВВГнг(А)-LS,1,AOT-0330/1
14,#0330,C1,X1,X1,АВ2,АВ2,6.0,ВВГнг(А)-LS,1,AOT-0330/1
15,#0330,N,X1,X1,АВ2,АВ2,6.0,ВВГнг(А)-LS,1,AOT-0330/1
16,#0331,A2,X1,X1,SF10,SF10,6.0,ВВГнг(А)-LS,1,AOT-0331/1
17,#0331,B2,X1,X1,SF10,SF10,6.0,ВВГнг(А)-LS,1,AOT-0331/1
18,#0331,C2,X1,X1,SF10,SF10,6.0,ВВГнг(А)-LS,1,AOT-0331/1
19,#0331,N,X1,X1,SF10,SF10,6.0,ВВГнг(А)-LS,1,AOT-0331/1
20,#0332,8001,X4,X4,1РТ,1РТ,1.5,КВВГЭнг(A)-LS,1,AOT-0332/1
21,#0332,8002,X4,X4,1РТ,1РТ,1.5,КВВГЭнг(A)-LS,1,AOT-0332/1
22,#0437,8001,X6,X6,2Т,2Т,1.5,КВВГЭнг(A)-LS,1,AOT-0437/1
23,#0437,8002,X6,X6,2Т,2Т,1.5,КВВГЭнг(A)-LS,1,AOT-0437/1
24,#0446,Ц135,X3,X3,X1,X1,1.5,КВВГЭнг(A)-LS,1,AOT-0446/1
25,#0446,A303,X4,X4,X1,X1,1.5,КВВГЭнг(A)-LS,2,AOT-0446/2
26,#0446,N,X4,X4,X1,X1,1.5,КВВГЭнг(A)-LS,2,AOT-0446/2
27,#0537,8001,X4,X4,2ВТ,2ВТ,1.5,КВВГЭнг(A)-LS,1,AOT-0537/1
28,#0537,8002,X4,X4,2ВТ,2ВТ,1.5,КВВГЭнг(A)-LS,1,AOT-0537/1
29,#0549,A1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0549/1
30,#0549,B1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0549/1
31,#0549,C1,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0549/1
32,#0549,N,X1,X1,SF14,SF14,2.5,ВВГнг(А)-LS,1,AOT-0549/1
33,#0550,A2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0550/1
34,#0550,B2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0550/1
35,#0550,C2,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0550/1
36,#0550,N,X1,X1,SF10,SF10,4.0,ВВГнг(А)-LS,1,AOT-0550/1
37,#0553,A12,X3,X3,X1,X1,1.5,КВВГЭнг(A)-LS,1,AOT-0553/1
38,#0553,A13,X3,X3,X1,X1,1.5,КВВГЭнг(A)-LS,1,AOT-0553/1
39,#0553,A15,X3,X3,X1,X1,1.5,КВВГЭнг(A)-LS,1,AOT-0553/1
40,#0553,0701,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
41,#0553,911,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
42,#0553,P1,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
43,#0553,P11,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
44,#0553,P14,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
45,#0553,P9,X5,X5,XT,XT,1.5,КВВГЭнг(A)-LS,2,AOT-0553/2
46,#0631,A2,X1,X1,АВ3,АВ3,10.0,ВВГнг(А)-LS,1,AOT-0631/1
47,#0631,B2,X1,X1,АВ3,АВ3,10.0,ВВГнг(А)-LS,1,AOT-0631/1
48,#0631,C2,X1,X1,АВ3,АВ3,10.0,ВВГнг(А)-LS,1,AOT-0631/1
49,#0631,N,X1,X1,АВ3,АВ3,10.0,ВВГнг(А)-LS,1,AOT-0631/1
50,#0637,8001,X4,X4,2РТ,2РТ,1.5,КВВГЭнг(A)-LS,1,AOT-0637/1
51,#0637,8002,X4,X4,2РТ,2РТ,1.5,КВВГЭнг(A)-LS,1,AOT-0637/1
52,#0651,A1,X1,X1,SF14,SF14,10.0,ВВГнг(А)-LS,1,AOT-0651/1
53,#0651,B1,X1,X1,SF14,SF14,10.0,ВВГнг(А)-LS,1,AOT-0651/1
54,#0651,C1,X1,X1,SF14,SF14,10.0,ВВГнг(А)-LS,1,AOT-0651/1
55,#0651,N,X1,X1,SF14,SF14,10.0,ВВГнг(А)-LS,1,AOT-0651/1

#### Длины направлений для внетренних и внешних участков

In [26]:
from src.out_connect.misc import used_direction

used_direction(station, cables_collection)

{}

{"#0132":  139, "#0209":   55, "#0210":  106, "#0232":  147, "#0330":  165, "#0331":  161, "#0332":  153,
 "#0437":  172, "#0446":   57, "#0537":  178, "#0549":   53, "#0550":  105, "#0553":   22, "#0631":  203,
 "#0637":  198, "#0651":  211, }

## Список клеммников и жил в шкафах

In [27]:
used_clemms(station, clemmnic_data, f"{plot_dir}/Схемы/Клеммники.xlsx")
used_wires(contact_data, clemmnic_data, f"{plot_dir}/Схемы/Жилы.xlsx")

## Общие данные

### Список шкафов

In [28]:
def save_cabinet_table(station, file_name):
    config = station.conf.cabine_list
    columns = ["Номер", "Обозначение", "Наименование", "Примечание"]
    table_width = config.table_width
    header_table = [columns]
    rows_in_table = config.rows_in_table
    start_possition = {"X": config.start_possition[0], "Y": config.start_possition[1]}
    print_table1 = pandas.DataFrame(make_cabinet_table(station)).to_numpy()

    height = pl.HEIGHT
    pl.HEIGHT = config.height
    pl.plot_split_table(
        print_table1,
        header_table,
        table_width,
        rows_in_table,
        rows_in_table,
        start_possition,
        file_name,
        delta=config.delta,
        align=["c", "c", "l", "c"],
    )

    _ = shutil.copyfile(
        file_name, f"{output_dir}/{basename(file_name)[:-4]}-{unixtime}.lsp"
    )

    pl.HEIGHT = height

In [29]:
save_cabinet_table(
    station, f"{plot_dir}/Схемы/ОД. Печать списка шкафов для принципиалок.lsp"
)

### Заполнение листа общих данных

In [30]:
print_work_scheme(
    station, f"{plot_dir}/Схемы/ОД. Рабочие, ссылочные и прилагаемые чертежи.lsp", 20, 292
)

### Заполнение первых листов основного комплекта

In [31]:
print_schemes_name(
    station, f"{plot_dir}/Схемы/ОД. Заполнение первых листов основного комплекта.lsp", -1000, -297, 1
)

### Список устройств с информацией о контактах

#### Вывод в Autocad

In [32]:
def plot_devices(station, data_pandas, file_name):
    config = station.conf.devices_list
    rows_in_first_sheet = config.rows_in_first_sheet
    rows_in_other_sheet = config.rows_in_other_sheet
    start_possition = {"X": config.start_possition[0], "Y": config.start_possition[1]}
    table_width = config.table_width
    ksize_font = 7 * [3.2 / 5]
    align = ["c", "l", "l", "l", "c", "l", "l"]

    data_numpy = data_pandas.to_numpy()
    header_table = [list(data_pandas.columns)]

    pl.plot_split_table(
        fit_data(
            data_numpy,
            table_width,
            ksize_font=ksize_font,
            delim=" ",
            add_blank_line=False,
        ),
        header_table,
        table_width,
        rows_in_first_sheet,
        rows_in_other_sheet,
        start_possition,
        file_name,
        delta=config.delta,
        align=align,
    )

    _ = shutil.copyfile(
        file_name, f"{output_dir}/{basename(file_name)[:-4]}-{unixtime}.lsp"
    )

In [33]:
plot_devices(
    station,
    device_list(station, contact_data, device_data),
    f"{plot_dir}/Схемы/ОД. Печать списка устойств c контактами для принципиалок.lsp",
)

#### Вывод в Excel и Csv

In [34]:
def used_devices_with_contacts(station, contact_data, device_data, file_name):
    with safe_excel_writer(file_name) as writer:
        for cabin_num in station.show_contacts_cabines():
            closet_device = view_devices_with_contacts(
                station, contact_data, device_data, cabin_num, add_closet=False
            )
            if not closet_device.empty:
                cabin = get_short_cabinet_name(station, int(cabin_num))
                closet_device.to_excel(writer, sheet_name=cabin, index=False)

def used_devices_with_contacts_to_csv(station, contact_data, device_data, file_name):
    df = pandas.DataFrame()
    cabins = []
    for cabin_num in station.show_contacts_cabines():
        new_df = view_devices_with_contacts(
             station,
             contact_data,
             device_data,
             cabin_num,
             add_closet=False,
             add_blank_line=False
         )
        df = pandas.concat([df, new_df])
        cabins += len(new_df) * [cabin_num]
    df["ШКАФ"] = cabins
    safe_to_csv(df, file_name, index=False)

    _ = shutil.copyfile(
        file_name, f"{output_dir}/{basename(file_name)[:-4]}-{unixtime}.csv"
    )

In [35]:
used_devices_with_contacts(
    station, contact_data, device_data, f"{plot_dir}/Схемы/Спецификация устойств.xlsx"
)

used_devices_with_contacts_to_csv(
    station,
    contact_data,
    device_data,
    f"{plot_dir}/Схемы/ОД. Печать списка устойств c контактами для принципиалок.csv"
)

## Формирование кабельно жирнала

### Список жил

In [36]:
list_wires = make_wires_journal(station, cables_collection, clemmnic_data)

name_file = f"{output_dir}/Жилы-{unixtime}"
list_wires_pandas = pandas.DataFrame(list_wires)
safe_to_excel(list_wires_pandas, name_file + ".xlsx", index=False)
safe_to_csv(list_wires_pandas, name_file + ".csv", index=False)

safe_to_excel(list_wires_pandas, f"{plot_dir}/КЖ/Excel Список жил.xlsx", index=False)

lisp_list_wires = pl.plot_table(
    shrink_long_string(list_wires_pandas.to_numpy()),
    [36, 36, 26, 25, 240, 32],
    align=["c", "c", "c", "c", "l", "c"],
)
AutocadElements(lisp_list_wires).save(f"{plot_dir}/КЖ/Печать списка жил.lsp")

list_wires_pandas

,Наименование кабеля,Тип,Кол-во и сечение жил,Кол-во исп. жил,Маркировка используемых жил в кабеле,Примечание
0,AOT-0132/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
1,AOT-0209/1,ВВГнг(А)-LS,5x2.5,4,"A1, B1, C1, N",
2,AOT-0210/1,ВВГнг(А)-LS,5x4.0,4,"A2, B2, C2, N",
3,AOT-0232/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
4,AOT-0330/1,ВВГнг(А)-LS,5x6.0,4,"A1, B1, C1, N",
5,AOT-0331/1,ВВГнг(А)-LS,5x6.0,4,"A2, B2, C2, N",
6,AOT-0332/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
7,AOT-0437/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
8,AOT-0446/1,КВВГЭнг(A)-LS,4x1.5,1,Ц135,
9,AOT-0446/2,КВВГЭнг(A)-LS,4x1.5,2,"A303, N",
10,AOT-0537/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
11,AOT-0549/1,ВВГнг(А)-LS,5x2.5,4,"A1, B1, C1, N",
12,AOT-0550/1,ВВГнг(А)-LS,5x4.0,4,"A2, B2, C2, N",
13,AOT-0553/1,КВВГЭнг(A)-LS,4x1.5,3,"A12, A13, A15",
14,AOT-0553/2,КВВГЭнг(A)-LS,10x1.5,6,"0701, 911, P1, P11, P14, P9",
15,AOT-0631/1,ВВГнг(А)-LS,5x10.0,4,"A2, B2, C2, N",
16,AOT-0637/1,КВВГЭнг(A)-LS,4x1.5,2,"8001, 8002",
17,AOT-0651/1,ВВГнг(А)-LS,5x10.0,4,"A1, B1, C1, N",
18,МО-1НL28-12,КВВГЭ-нг,19x2.5,28,"1SL00K008, 1SP10K001, 1SP10K003, +24В, 1SP10K0...",(Сущ.)
19,1GT-143,КВВГЭ-нг,19x2.5,3,"1-HA03, Р11.2-А, Р11.3-А",(Сущ.)
20,1GT-243,КВВГЭ-нг,19x2.5,3,"1-HA04, Р11.2-Б, Р11.3-Б",(Сущ.)
21,1ST-1241,КВВГЭ-нг,19x2.5,0,,(Сущ.)
22,0BT-226,КВВГЭ-нг,19x2.5,6,"A12, N, A15, A13, A14, 117",(Сущ.)
23,1BT-300,КВВГЭ-нг,19x2.5,8,"117, A11, A1, 8007, 8003, P13, N, 8141",(Сущ.)
24,1BT-197,КВВГЭ-нг,19x2.5,5,"A12, N, A14, A11, 117",(Сущ.)
25,1GT-107,КВВГЭ-нг,19x2.5,15,"Ц127, Ц133, Ц136, 915, Ц102, 1-HA03, 131а, 131...",(Сущ.)
26,K58,КВВГЭ-нг,19x2.5,4,"A1, 8007, 8003, H1-4",(Сущ.)
27,0BT02k191,КВВГЭ-нг,19x2.5,11,"B4(1), 10701, 9(11), 923, 921, 925, 923, B4(1)...",(Сущ.)
28,СОТ1к1190,КВВГЭ-нг,19x2.5,18,"Ц131, 916, 917, 919, 920, 921, 922, 923, 927, ...",(Сущ.)
29,1GT-331,КВВГЭ-нг,19x2.5,16,"Ц135, Ц133, Ц101, Ц127, A108, A109, A110, A303...",(Сущ.)
30,1GTk1239,КВВГЭ-нг,19x2.5,4,"A11, A12, A20, A19",(Сущ.)
31,1BT-198,КВВГЭ-нг,19x2.5,3,"A12, A15, A13",(Сущ.)
32,ШАОТ-1Т,КВВГЭ-нг,19x2.5,2,"A301, A303",(Сущ.)
33,1GT-101,КВВГЭ-нг,19x2.5,2,"Ц107, Ц101",(Сущ.)
34,ED-1GT-105,КВВГЭ-нг,19x2.5,4,"Ц101, Ц102, Ц101, Ц102",(Сущ.)
35,1GT-100,КВВГЭ-нг,19x2.5,2,"Ц105, Ц107",(Сущ.)
36,1GT-102,КВВГЭ-нг,19x2.5,2,"Ц107, Ц109",(Сущ.)
37,1GT-106,КВВГЭ-нг,19x2.5,2,"Ц107, Ц109",(Сущ.)
38,к32,АВВГ,4x95,8,"A1, B1, C1, N, A1, B1, C1, N",(Сущ.)
39,к33,АВВГ,4x95,8,"A2, B2, C2, N, A2, B2, C2, N",(Сущ.)
40,1ВТ-02,ВВГ,4x4,0,,(Сущ.)
41,1РТСН-02,ВВГ,4x4,0,,(Сущ.)
42,к100,АВВГ,4x120,8,"A1, B1, C1, N, A1, B1, C1, N",(Сущ.)
43,к101,АВВГ,4x120,8,"A2, B2, C2, N, A2, B2, C2, N",(Сущ.)
44,2BT01-300,КВВГЭ-нг,19x2.5,2,"A17, A18",(Сущ.)
45,2ВТ-02,ВВГ,4x4,0,,(Сущ.)
46,2РТСН-02,ВВГ,4x4,0,,(Сущ.)
47,2SP10k331,КВВГЭ-нг,19x2.5,3,"65, 37, 43",(Сущ.)

### Кабельный журнал

In [37]:
cable_journal = make_cable_journal(station, cables_collection)

name_file = f"{output_dir}/КЖ-{unixtime}"
cable_journal_pandas = pandas.DataFrame(cable_journal)
safe_to_excel(cable_journal_pandas, name_file + ".xlsx", index=False)
safe_to_csv(cable_journal_pandas, name_file + ".csv", index=False)

safe_to_excel(list_wires_pandas, f"{plot_dir}/КЖ/Excel Кабельный журнал.xlsx", index=False)

lisp_cable_journal = pl.plot_table(
    shrink_long_string(cable_journal_pandas.to_numpy()),
    [25, 35, 20, 120, 120, 15, 15, 15, 30],
    offset=(-395, 0),
    align=["c", "c", "c", "l", "l", "c", "c", "c", "c"],
)
AutocadElements(lisp_cable_journal).save(f"{plot_dir}/КЖ/Печать КЖ.lsp")

cable_journal_pandas

,Наименование кабеля,Тип,Жилы,Первая точка,Вторая точка,Длинна,Проложено,Монт. ед,Примечание
0,AOT-0132/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","ПТК Б1, Шкаф сбора данных в ПТК АСУ-ТП Блока 1",146,,1,
1,AOT-0209/1,ВВГнг(А)-LS,5x2.5,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","1DP03, Сборка РТЗО 1DP03 шк.2",58,,2,
2,AOT-0210/1,ВВГнг(А)-LS,5x4.0,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","1DQ02, Сборка РТЗО 1DQ02 шк.2",112,,3,
3,AOT-0232/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","ПТК Б1, Шкаф сбора данных в ПТК АСУ-ТП Блока 1",155,,4,
4,AOT-0330/1,ВВГнг(А)-LS,5x6.0,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","ODH12, Сборка РТЗО ODH12 шк.2",174,,5,
5,AOT-0331/1,ВВГнг(А)-LS,5x6.0,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","ODJ05, Сборка КТПСН ODJ05 шк.1",170,,6,
6,AOT-0332/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","ПТК Б1, Шкаф сбора данных в ПТК АСУ-ТП Блока 1",161,,7,
7,AOT-0437/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2Т, Охлаждение тр-ра 2Т","ПТК Б2, Шкаф сбора данных в ПТК АСУ-ТП Блока 2",181,,8,
8,AOT-0446/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2Т, Охлаждение тр-ра 2Т","ККТ 2Т, Кросс шкаф трансформатора 2Т",60,,9,
9,AOT-0446/2,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2Т, Охлаждение тр-ра 2Т","ККТ 2Т, Кросс шкаф трансформатора 2Т",60,,10,
10,AOT-0537/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2ВТ, Охлаждение 2ВТ","ПТК Б2, Шкаф сбора данных в ПТК АСУ-ТП Блока 2",187,,11,
11,AOT-0549/1,ВВГнг(А)-LS,5x2.5,"ШАОТ 2ВТ, Охлаждение 2ВТ","2DP03, Сборка РТЗО 2DP03 шк.2",56,,12,
12,AOT-0550/1,ВВГнг(А)-LS,5x4.0,"ШАОТ 2ВТ, Охлаждение 2ВТ","2DQ01, Сборка КТПСН 2DQ01 шк.1",111,,13,
13,AOT-0553/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2ВТ, Охлаждение 2ВТ","ККТ 2ВТ, Кросс шкаф трансформатора 2ВТ",24,,14,
14,AOT-0553/2,КВВГЭнг(A)-LS,10x1.5,"ШАОТ 2ВТ, Охлаждение 2ВТ","ККТ 2ВТ, Кросс шкаф трансформатора 2ВТ",24,,15,
15,AOT-0631/1,ВВГнг(А)-LS,5x10.0,"ШАОТ 2РТСН, Охлаждение 2РТСН","ODJ05, Сборка КТПСН ODJ05 шк.1",214,,16,
16,AOT-0637/1,КВВГЭнг(A)-LS,4x1.5,"ШАОТ 2РТСН, Охлаждение 2РТСН","ПТК Б2, Шкаф сбора данных в ПТК АСУ-ТП Блока 2",208,,17,
17,AOT-0651/1,ВВГнг(А)-LS,5x10.0,"ШАОТ 2РТСН, Охлаждение 2РТСН","ODH11, Сборка РТЗО ODH11 шк.2",222,,18,
18,МО-1НL28-12,КВВГЭ-нг,19x2.5,"1HL28, Шкаф сбора данных в ПТК АСУ-ТП","Пр.шк., Промежаточный шкаф охлаждения 1Т",100,,19,(Сущ.)
19,1GT-143,КВВГЭ-нг,19x2.5,"1HA03,","Пр.шк., Промежаточный шкаф охлаждения 1Т",100,,20,(Сущ.)
20,1GT-243,КВВГЭ-нг,19x2.5,"1HA04,","Пр.шк., Промежаточный шкаф охлаждения 1Т",100,,21,(Сущ.)
21,1ST-1241,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","ККТ 1Т, Кросс шкаф трансформатора 1Т",100,,22,(Сущ.)
22,0BT-226,КВВГЭ-нг,19x2.5,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","ККТ 1РТСН, Кросс шкаф трансформатора 1РТСН",100,,23,(Сущ.)
23,1BT-300,КВВГЭ-нг,19x2.5,"1HA12,","ККТ 1ВТ, Кросс шкаф трансформатора 1ВТ",100,,24,(Сущ.)
24,1BT-197,КВВГЭ-нг,19x2.5,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","ККТ 1ВТ, Кросс шкаф трансформатора 1ВТ",100,,25,(Сущ.)
25,1GT-107,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","Пр.шк., Промежаточный шкаф охлаждения 1Т",100,,26,(Сущ.)
26,K58,КВВГЭ-нг,19x2.5,"1HA12,","КШ24, Шкаф сбора данных в ПТК АСУ-ТП",100,,27,(Сущ.)
27,0BT02k191,КВВГЭ-нг,19x2.5,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","п.8, Защиты 1РТСН",100,,28,(Сущ.)
28,СОТ1к1190,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","Пр.шк., Промежаточный шкаф охлаждения 1Т",100,,29,(Сущ.)
29,1GT-331,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","ККТ 1Т, Кросс шкаф трансформатора 1Т",100,,30,(Сущ.)
30,1GTk1239,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","РТЗО 81, Сборка РТЗО",100,,31,(Сущ.)
31,1BT-198,КВВГЭ-нг,19x2.5,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","ККТ 1ВТ, Кросс шкаф трансформатора 1ВТ",100,,32,(Сущ.)
32,ШАОТ-1Т,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1HZ70A02, Шкаф автоматики пажаротушения тр-ра 1Т",100,,33,(Сущ.)
33,1GT-101,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","11P,",100,,34,(Сущ.)
34,ED-1GT-105,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1HA11,",100,,35,(Сущ.)
35,1GT-100,КВВГЭ-нг,19x2.5,"11P,","12P,",100,,36,(Сущ.)
36,1GT-102,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1HA05,",100,,37,(Сущ.)
37,1GT-106,КВВГЭ-нг,19x2.5,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1ШУС, Шкаф управления и сигнализации",100,,38,(Сущ.)
38,к32,АВВГ,4x95,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1СР01, Секция 1СР01, шкаф 4",100,,39,(Сущ.)
39,к33,АВВГ,4x95,"ШАОТ 1Т, Охлаждение тр-ра 1Т","1СQ01, Секция 1СQ01, шкаф 2",100,,40,(Сущ.)
40,1ВТ-02,ВВГ,4x4,"ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ","1DP03, Сборка РТЗО 1DP03 шк.2",100,,41,(Сущ.)
41,1РТСН-02,ВВГ,4x4,"ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН","ODH12, Сборка РТЗО ODH12 шк.2",100,,42,(Сущ.)
42,к100,АВВГ,4x120,"ШАОТ 2Т, Охлаждение тр-ра 2Т","2CP01, Секция 2СР01, шкаф 4",100,,43,(Сущ.)
43,к101,АВВГ,4x120,"ШАОТ 2Т, Охлаждение тр-ра 2Т","2CQ01, Секция 2СQ01, шкаф 2",100,,44,(Сущ.)
44,2BT01-300,КВВГЭ-нг,19x2.5,"ШАОТ 2ВТ, Охлаждение 2ВТ","РПН 2ВТ, Трансформатор 2ВТ",100,,45,(Сущ.)
45,2ВТ-02,ВВГ,4x4,"ШАОТ 2ВТ, Охлаждение 2ВТ","2DP03, Сборка РТЗО 2DP03 шк.2",100,,46,(Сущ.)
46,2РТСН-02,ВВГ,4x4,"ШАОТ 2РТСН, Охлаждение 2РТСН","ODH11, Сборка РТЗО ODH11 шк.2",100,,47,(Сущ.)
47,2SP10k331,КВВГЭ-нг,19x2.5,"ШАОТ 2Т, Охлаждение тр-ра 2Т","ККТ 2Т, Кросс шкаф трансформатора 2Т",100,,48,(Сущ.)

### Формирование схем кабельных связей

In [38]:
from src.out_connect.cable_journal import CableLinks

lisp_cable_links = CableLinks(station, cables_collection).plot_cable_link()
AutocadElements(lisp_cable_links).save(
    f"{plot_dir}/КЖ/Печать схемы кабельных связей.lsp"
)
out = shutil.copyfile(
    f"{plot_dir}/КЖ/Печать схемы кабельных связей.lsp",
    f"{output_dir}/Печать схемы кабельных связей-{unixtime}.lsp",
)

In [39]:
# Общий файл содержащий КЖ, Список жил и Схему кабельных связей
AutocadElements(lisp_cable_links + lisp_cable_journal + lisp_list_wires).save(
    f"{plot_dir}/КЖ/Общий скрипт кабельного журнала.lsp"
)

## Построения монтажных схем

In [40]:
def montage_scheme(frame):
    montage_cable.station = station
    montage_cable.cables_collection = cables_collection
    montage_cable.contact_data = contact_data
    montage_cable.clemmnic_data = clemmnic_data

    montage = montage_cable.MontageCable(frame)
    montage_data = montage.get_montage()

    montage_sheets = montage.get_contents()
    montage_sheets_pandas = pandas.DataFrame(montage_sheets, index=["Листы"]).T
    summer = {"Шкафы": [], "Листы": []}
    for i, row in montage_sheets_pandas.iterrows():
        summer["Шкафы"].append(i)
        summer["Листы"].append(row["Листы"])

    print_table = pandas.DataFrame(summer).to_numpy()
    sheet_data = pl.plot_table(
        print_table, [120, 30], offset=(50, 350), align=["l", "l"]
    )

    AutocadElements(sheet_data + montage_data).save(
        f"{plot_dir}/Монтажки/Монтажные схемы подключения кабелей.lsp"
    )
    shutil.copyfile(
        f"{plot_dir}/Монтажки/Монтажные схемы подключения кабелей.lsp",
        f"{output_dir}/Монтажные схемы подключения кабелей-{unixtime}.lsp",
    )

    safe_to_csv(
        pandas.DataFrame(montage_cable.montage_scheme_array()),
        f"{plot_dir}/Монтажки/Монтажные схемы подключения кабелей.csv",
        sep=";",
        index=False,
    )
    shutil.copyfile(
        f"{plot_dir}/Монтажки/Монтажные схемы подключения кабелей.csv",
        f"{output_dir}/Монтажные схемы подключения кабелей-{unixtime}.csv",
    )

    return montage_sheets_pandas

def save_cores_notes():
    montage_cable.station = station
    montage_cable.cables_collection = cables_collection
    montage_cable.contact_data = contact_data
    montage_cable.clemmnic_data = clemmnic_data

    montage_cable.output_clemmnics(0, 4, f"{plot_dir}/Схемы/Маркеровка жил на трубку 4мм (S жил до 4мм2).xlsx")
    montage_cable.output_clemmnics(4, 16, f"{plot_dir}/Схемы/Маркеровка жил на трубку 6мм и более (S жил от 4мм2 до 16мм2).xlsx")

### Монтажные схемы

In [41]:
montage_scheme(frame=montage_cable.A3)

                                                Листы
ШАОТ 1Т, Охлаждение тр-ра 1Т                    2 - 3
ШАОТ 1ВТ, Охлаждение тр-ра 1ВТ                      3
ШАОТ 1РТСН, Охлаждение тр-ра 1РТСН                  4
ШАОТ 2Т, Охлаждение тр-ра 2Т                    4 - 5
ШАОТ 2ВТ, Охлаждение 2ВТ                        5 - 6
ШАОТ 2РТСН, Охлаждение 2РТСН                    6 - 7
1DQ02, Сборка РТЗО 1DQ02 шк.2                       7
ODH12, Сборка РТЗО ODH12 шк.2                       7
ODJ05, Сборка КТПСН ODJ05 шк.1                      7
ПТК Б1, Шкаф сбора данных в ПТК АСУ-ТП Блока 1      7
ПТК Б2, Шкаф сбора данных в ПТК АСУ-ТП Блока 2  7 - 8
ККТ 2Т, Кросс шкаф трансформатора 2Т                8
2DP03, Сборка РТЗО 2DP03 шк.2                       8
2DQ01, Сборка КТПСН 2DQ01 шк.1                      9
ODH11, Сборка РТЗО ODH11 шк.2                       9
ККТ 2ВТ, Кросс шкаф трансформатора 2ВТ              9

### Маркеровка жил

In [42]:
save_cores_notes()

### Протокол проверки изоляции кабелей

In [43]:
if 'isolation' in station.conf and station.conf.isolation == True:
    isolation = isolation_cables.Isolation(
        station,
        cables_collection,
        contact_data,
        clemmnic_data,
        generate_r=station.conf.isolation_gen if 'isolation_gen' in station.conf else False
    )
    safe_to_excel(
        pandas.DataFrame(isolation()),
        f"{plot_dir}/Протокол проверки изоляции кабелей.xlsx",
        index=False
    )

## Инициализация кабелей в принципиальных схемах

In [44]:
from src.out_connect.define_cables import (
    set_cable_name,
    get_cable_without_names,
    get_cable_with_name_equal_direction
)

In [45]:
cables_data = set_cable_name(station, cables_collection)

In [46]:
get_cable_without_names(cables_data)

Empty DataFrame
Columns: []
Index: []

In [47]:
get_cable_with_name_equal_direction(cables_data)

Empty DataFrame
Columns: []
Index: []

In [48]:
def save_init_cables_name(cables_data):
    safe_to_csv(
        pandas.DataFrame(cables_data),
        f"{plot_dir}/Схемы/Загрузка инициализированных кабелей в чертеж Autocad.txt",
        sep="\t",
        encoding="cp1251",
        index=False,
    )
    shutil.copyfile(
        f"{plot_dir}/Схемы/Загрузка инициализированных кабелей в чертеж Autocad.txt",
        f"{output_dir}/Загрузка инициализированных кабелей в чертеж Autocad-{unixtime}.txt",
    )

In [49]:
save_init_cables_name(cables_data)

## Инициализация ссылок на листы

In [50]:
from src.out_connect import define_reference

In [51]:
init_reference = define_reference.init_reference(station, contact_data, clemmnic_data)
pandas.DataFrame(init_reference)

     HANDLE BLOCKNAME ТЕКСТ MAJOR MINOR X Y                 ID
0   '37723B       REF   см.     2     1         ШАОТ 1Т:SF11:2
1   '37724B       REF   см.     2     8           ШАОТ 1Т:Z1:3
2   '377254       REF   см.     2     6          ШАОТ 1Т:SQ1:1
3   '37725C       REF   см.     2     3           ШАОТ 1Т:X4:4
4   '377AAB       REF   см.     2     1         ШАОТ 1Т:SF12:2
5   '37838A       REF   см.     3     4          ШАОТ 1ВТ:Z1:3
6   '378392       REF   см.     3     3         ШАОТ 1ВТ:SQ1:1
7   '37839A       REF   см.     4     4        ШАОТ 1РТСН:Z1:3
8   '3783A2       REF   см.     4     3       ШАОТ 1РТСН:SQ1:1
9   '378BE9       REF   см.     3     1        ШАОТ 1ВТ:SF11:2
10  '378BF1       REF   см.     3     1        ШАОТ 1ВТ:SF10:2
11  '378BF9       REF   см.     4     1      ШАОТ 1РТСН:SF11:2
12  '378C01       REF   см.     4     1      ШАОТ 1РТСН:SF10:2
13  '3D687B       REF   см.     5     1         ШАОТ 2Т:SF11:2
14  '3D689C       REF   см.     5     1         ШАОТ 2Т:SF12:2
15  '3DDF97       REF   см.     6     4          ШАОТ 2ВТ:Z1:3
16  '3DDF9F       REF   см.     6     3         ШАОТ 2ВТ:SQ1:1
17  '3DDFA7       REF   см.     6     1        ШАОТ 2ВТ:SF11:2
18  '3DDFAF       REF   см.     6     1        ШАОТ 2ВТ:SF10:2
19  '3E19BF       REF   см.     7     4        ШАОТ 2РТСН:Z1:3
20  '3E19C7       REF   см.     7     3       ШАОТ 2РТСН:SQ1:1
21  '3E19CF       REF   см.     7     1      ШАОТ 2РТСН:SF11:2
22  '3E19D7       REF   см.     7     1      ШАОТ 2РТСН:SF10:2
23  '654337       REF   см.     2     1          ШАОТ 1Т:KM2:1
24  '65433F       REF   см.     2     1          ШАОТ 1Т:KM3:1
25  '654347       REF   см.     2     1          ШАОТ 1Т:KM4:1
26  '65434F       REF   см.     2     1          ШАОТ 1Т:KM5:1
27  '654357       REF   см.     2     1          ШАОТ 1Т:KM6:1
28  '65435F       REF   см.     2     1          ШАОТ 1Т:KM7:1
29  '654367       REF   см.     2     2          ШАОТ 1Т:K23:1
30  '65436F       REF   см.     2     2          ШАОТ 1Т:K23:3
31  '654377       REF   см.     2     2          ШАОТ 1Т:K23:5
32  '65437F       REF   см.     2     2         ШАОТ 1Т:K23:13
33  '654387       REF   см.     2     2        ШАОТ 1Т:K23.1:3
34  '65438F       REF   см.     2     2          ШАОТ 1Т:SA3:2
35  '654397       REF   см.     2     1         ШАОТ 1Т:KM10:1
36  '65439F       REF   см.     2     3          ШАОТ 1Т:SA4:2
37  '657BB6       REF   см.     5     2          ШАОТ 2Т:SA3:2
38  '657BBE       REF   см.     5     2          ШАОТ 2Т:K23:1
39  '657BC6       REF   см.     5     2          ШАОТ 2Т:K23:3
40  '657BCE       REF   см.     5     2          ШАОТ 2Т:K23:5
41  '657BD6       REF   см.     5     2         ШАОТ 2Т:K23:13
42  '657BDE       REF   см.     5     2        ШАОТ 2Т:K23.1:3
43  '657BE6       REF   см.     5     3          ШАОТ 2Т:SA4:2
44  '657BEE       REF   см.     5     1          ШАОТ 2Т:KM8:1
45  '657BF6       REF   см.     5     1          ШАОТ 2Т:KM6:1
46  '657BFE       REF   см.     5     1          ШАОТ 2Т:KM7:3
47  '657C06       REF   см.     5     1          ШАОТ 2Т:KM5:1
48  '657C0E       REF   см.     5     1          ШАОТ 2Т:KM4:1
49  '657C16       REF   см.     5     1          ШАОТ 2Т:KM3:1
50  '657C1E       REF   см.     5     1          ШАОТ 2Т:KM2:1
51  '657C26       REF   см.     5     3          ШАОТ 2Т:K21:1
52  '657C2E       REF   см.     5     1          ШАОТ 2Т:KM1:1
53  '657C36       REF   см.     5     1         ШАОТ 2Т:SF13:2
54  '657C3E       REF   см.     5     1           ШАОТ 2Т:X3:1
55  '658A41       REF   см.     5     1         ШАОТ 2Т:KM10:1
56  '782B19       REF   см.     2     3          ШАОТ 1Т:K21:1

In [52]:
safe_to_csv(
    pandas.DataFrame(init_reference),
    f"{plot_dir}/Схемы/Загрузка инициализированных ссылок в чертеж Autocad.txt",
    sep="\t",
    encoding="cp1251",
    index=False,
)

## Спецификация

### Длины и количество участнов

In [53]:
total_length = total_length_journal(station, cables_collection)
safe_to_excel(
    pandas.DataFrame(total_length, index=["Длинна"]).T,
    f"{plot_dir}/Итоговые длины.xlsx"
)
safe_to_csv(
    pandas.DataFrame(total_length, index=["Длинна"]).T,
    f"{output_dir}/Итоговые длины-{unixtime}.csv"
)
pandas.DataFrame(total_length, index=["Длинна"]).T

                      Длинна
КВВГЭнг(A)-LS 4x1.5     1182
ВВГнг(А)-LS 5x2.5        114
ВВГнг(А)-LS 5x4.0        223
ВВГнг(А)-LS 5x6.0        344
КВВГЭнг(A)-LS 10x1.5      24
ВВГнг(А)-LS 5x10.0       436

In [54]:
count_section = count_section_journal(cables_collection)
safe_to_csv(
    pandas.DataFrame(count_section, index=["Количество участков"]).T,
    f"{output_dir}/Итоговое количество участков-{unixtime}.csv"
)
pandas.DataFrame(count_section, index=["Количество участков"]).T

                      Количество участков
КВВГЭнг(A)-LS 4x1.5                     9
ВВГнг(А)-LS 5x2.5                       2
ВВГнг(А)-LS 5x4.0                       2
ВВГнг(А)-LS 5x6.0                       2
КВВГЭнг(A)-LS 10x1.5                    1
ВВГнг(А)-LS 5x10.0                      2

### Количество и деаметр отверстий в шкафах

In [55]:
from src.holes import calc_count_hole
from src.holes import diameter_for_cabinet


def count_cables_in_cabiten(cabinet):
    result = {}
    for cable in cables_collection.cables():
        if cabinet not in cables_collection.get_cabins_by_cable(cable):
            continue
        result[cable] = cables_collection.section(cable)
    preset_cables = station.preset_cables()
    for cable in preset_cables:
        if cabinet not in preset_cables.directions(cable):
            continue
        result[cable] = preset_cables.get_type(cable) + " " + preset_cables.get_cores_gauge(cable)
    return result

In [56]:
for cabinet in station.cabine_holes():
    print(get_short_cabinet_name(station, int(cabinet)), end=":\t")
    for d, c in calc_count_hole(cabinet, cables_collection).items():
        print("М" + d, "-", str(c) + "шт", end=", ")
    print()

ШАОТ 1Т:	М20 - 3шт, М32 - 10шт,
ШАОТ 1ВТ:	М20 - 2шт, М25 - 2шт, М32 - 2шт,
ШАОТ 1РТСН:	М25 - 3шт, М20 - 1шт, М32 - 2шт,
ШАОТ 2Т:	М20 - 5шт, М32 - 1шт,
ШАОТ 2ВТ:	М20 - 3шт, М25 - 3шт, М32 - 1шт,
ШАОТ 2РТСН:	М32 - 2шт, М20 - 1шт, М25 - 1шт,

In [57]:
for cabinet in station.cabine_holes():
    print(get_short_cabinet_name(station, int(cabinet)), end=":\t")
    for d, c in diameter_for_cabinet(cabinet, cables_collection).items():
        print(d + "мм" + " - " + str(c) + "шт", end=", ")
    print()

ШАОТ 1Т:	12мм - 1шт, 21мм - 10шт, 13мм - 2шт,
ШАОТ 1ВТ:	14мм - 1шт, 16мм - 1шт, 12мм - 1шт, 21мм - 2шт, 15мм - 1шт,
ШАОТ 1РТСН:	17мм - 2шт, 12мм - 1шт, 21мм - 2шт, 15мм - 1шт,
ШАОТ 2Т:	12мм - 3шт, 13мм - 2шт, 21мм - 1шт,
ШАОТ 2ВТ:	12мм - 2шт, 14мм - 1шт, 16мм - 1шт, 17мм - 1шт, 21мм - 1шт, 15мм - 1шт,
ШАОТ 2РТСН:	20мм - 2шт, 12мм - 1шт, 15мм - 1шт,

### Список устройств в шкафах

#### Вывод в Excel

In [58]:
from src.out_connect.specification import (
    used_devices_for_specification,
    summary_equipment_schedule,
    generate_equipment_config
)

In [59]:
used_devices_for_specification(
    station,
    clemmnic_data.get_list_cabine(),
    device_data,
    f"{plot_dir}/Спецификация устойств для спецификации.xlsx",
)

safe_to_excel(
    pandas.DataFrame(
        summary_equipment_schedule(station, clemmnic_data, device_data)
    ),
    f"{plot_dir}/Сводна ведомость устойств спецификации.xlsx",
    sheet_name="Сводна ведомость"
)

if station.conf.cabines.generate_equipment_config:
    generate_equipment_config(clemmnic_data, device_data, f"{plot_dir}/Шкаф/Устройства/")

### Печеть спецификации устройств

In [60]:
from src.out_connect.specification import (
    spds_specification,
    spds_specification_excel,
    spds_specification_array
)

spds_array = spds_specification_array(
    station,
    cables_collection,
    clemmnic_data,
    device_data.get_device_for_spec
)

⚠️  WARNING: Шкаф: '02'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '02'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '03'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '03'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '05'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '05'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '06'. Устойство 'Полоса' добавляется в спецификацию повторно.
⚠️  WARNING: Шкаф: '06'. Устойство 'Полоса' добавляется в спецификацию повторно.

#### Вывод в AutoCad

In [61]:
spds_specification(spds_array, f"{plot_dir}/Спецификация к разделу.lsp")
_ = shutil.copyfile(
    f"{plot_dir}/Спецификация к разделу.lsp",
    f"{output_dir}/Спецификация к разделу-{unixtime}.lsp",
)

#### Вывод в Excel

In [62]:
spds_specification_excel(spds_array, f"{plot_dir}/Спецификация к разделу.xlsx", copy_to_csv=True)
_ = shutil.copyfile(
    f"{plot_dir}/Спецификация к разделу.csv",
    f"{output_dir}/Спецификация к разделу-{unixtime}.csv",
)

## Печать графа объединяющего шкафы и кабель-каналы

In [63]:
from src.out_connect.length_cable.length import ClosetsGraph
from src.graph_view import GraphView

In [64]:
import os.path

if os.path.exists(station.CABINE_FILE):
    closet_graph = ClosetsGraph(station)
    cable_chanel = GraphView(closet_graph.cabine).plot(
        closet_graph.boxes, closet_graph.closet_graph, (20, 150)
    )

    AutocadElements(cable_chanel).save(
        f"{plot_dir}/Схемы/Шкафы/Схема графа кабель-каналов.lsp"
    )
    out = shutil.copyfile(
        f"{plot_dir}/Схемы/Шкафы/Схема графа кабель-каналов.lsp",
        f"{output_dir}/Схема графа кабель-каналов-{unixtime}.lsp",
    )

# Отладка

In [65]:
import unittest
from src.test import TestOutput

In [66]:
TestOutput.UNIXTIME = unixtime
TestOutput.OUTPUT_DIR = output_dir
TestOutput.TEST_CASE = station.test_case()
TestOutput.generate_tests()
_ = unittest.main(argv=[""], verbosity=1, exit=False)

...............
----------------------------------------------------------------------
Ran 15 tests in 0.057s

OK